services:
  potato-identifier:
    build: .
    image: potato-identifier
    container_name: potato-identifier-app
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
      - NET_ADMIN
    user: "1000:1000"
    group_add:
      - "44"
      - "20"
    ports:
      - "0808:0808"
    devices:
      - "/dev/bus/usb/002/004:/dev/bus/usb/002/004"
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - /home/torizon/.Xauthority:/root/.Xauthority:rw
    environment:
      - DISPLAY=:0
      - GENICAM_GENTL64_PATH=/opt/pylon/lib
      - XDG_RUNTIME_DIR=/run/user/1000
      - XAUTHORITY=/root/.Xauthority
    stdin_open: true
    tty: true
